//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soumissionParticuliere
    {
        public int idSoumPart { get; set; }
        public int codeTypeExam { get; set; }
        public int codeEmploi { get; set; }
    
        public virtual Emploi Emploi { get; set; }
        public virtual TypeExamen TypeExamen { get; set; }
    }
}
