//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiNurseAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.soins = new HashSet<soin>();
        }
    
        public decimal idPatient { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime dateNaissance { get; set; }
        public string numTelephone { get; set; }
        public string email { get; set; }
        public string rue { get; set; }
        public decimal numeroMaison { get; set; }
        public decimal codePostal { get; set; }
        public string localite { get; set; }
        public System.DateTime dateDebutSoin { get; set; }
        public Nullable<System.DateTime> dateFinSoin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soin> soins { get; set; }
    }
}
