//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiNurseAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soin
    {
        public decimal idSoin { get; set; }
        public System.DateTime dateSoin { get; set; }
        public decimal idPatient { get; set; }
        public decimal idInfi { get; set; }
    
        public virtual infirmier infirmier { get; set; }
        public virtual patient patient { get; set; }
    }
}
