//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeExamen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeExamen()
        {
            this.ExamenRealise = new HashSet<ExamenRealise>();
            this.soumissionParticuliere = new HashSet<soumissionParticuliere>();
        }
    
        public int codeTypeExam { get; set; }
        public string typeExamen1 { get; set; }
        public decimal codeCompte { get; set; }
        public decimal prixSoumis { get; set; }
        public decimal prixNonSoumis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenRealise> ExamenRealise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soumissionParticuliere> soumissionParticuliere { get; set; }
    }
}
